name: Release website
on:
  push:
    tags:
      - '*'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
        with:
          # This will create a directory named `my-repo` and copy the repo contents to it
          # so that you can easily upload it to your remote server
          path: brakket
      - name: Prepare SSH
        run: >
          cd ~ && mkdir .ssh &&
          touch ~/.ssh/known_hosts &&
          ssh-keyscan -H "$IP" >>~/.ssh/known_hosts
        env:
          IP: ${{ secrets.IP }}
      - name: Upload repo to remote server
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "${{ secrets.PRIVATE_KEY }}"
          scp -o StrictHostKeyChecking=no -r  brakket root@${{ secrets.IP }}:/var/www/
          ssh -o ServerAliveInterval=3000 -o ServerAliveCountMax=100 root@${{ secrets.IP }} "cd /var/www/brakket/ && docker-compose down && docker-compose build --no-cache && docker-compose up -d"
#    steps:
#      - uses: actions/checkout@v1
#      - name: Push to server
#        uses: appleboy/ssh-action@master
#        with:
#          host: ${{ secrets.IP }}
#          username: root
#          password: ${{ secrets.PASSWORD }}
#          script: cd /var/www/brakket  && docker compose up
#      - name: Setup SSH
#        run: |
#          mkdir -p ~/.ssh/
#          echo "${{ secrets.SSH_PRIV_KEY }}" > ~/.ssh/id_rsa
#          echo "${{ secrets.SSH_PUB_KEY }}" > ~/.ssh/id_rsa.pub
#          chmod 600 ~/.ssh/id_rsa
#          chmod 600 ~/.ssh/id_rsa.pub
#          ssh-keyscan -H ${{ secrets.IP }} >> ~/.ssh/known_hosts
#      - name: copy builds to server
#        run: |
#          rsync -vrm   ./* ${{ secrets.USER_IP }}:/var/www/brakket/
#          ssh ${{ secrets.USER_IP }} "cd /var/www/brakket/ && docker compose up "